name: 'build-zlog-plugin'
author: 'The University of Tokyo Amateur Radio Club'
description: 'GitHub action that builds a ZyLO DLL and publishes it as a nightly build'
branding:
  icon: radio
  color: blue
inputs:
  ref:
    description: 'branch'
  tag:
    description: 'release name'
    default: nightly
  version:
    description: 'zLog version'
    default: '2.8'
  token:
    description: 'GITHUB_TOKEN'
    required: true
  directory:
    description: 'project path'
    default: '.'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{inputs.ref}}
  - uses: actions/setup-go@v3
    with:
      go-version: 1.18
  - name: zbuild
    run: |
      go install github.com/nextzlog/zylo/zbuild@HEAD
      zbuild setup --sudo || zbuild setup
      zbuild build --version ${{inputs.version}}
      gh release create ${{inputs.tag}} || true
      gh release upload ${{inputs.tag}} *.{dll,md5} --clobber
    shell: bash
    env:
      GOPROXY: direct
      GITHUB_TOKEN: ${{inputs.token}}
    working-directory: ${{inputs.directory}}
