name: 'build-zlog-plugin'
author: 'The University of Tokyo Amateur Radio Club'
description: 'GitHub action that builds a ZyLO DLL and publishes it as a nightly build'
branding:
  icon: radio
  color: blue
inputs:
  ref:
    description: 'branch'
    required: false
    default: ''
  tag:
    description: 'release name'
    required: false
    default: nightly
  token:
    description: 'GITHUB_TOKEN'
    required: true
  directory:
    description: 'project path'
    required: false
    default: '.'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{inputs.ref}}
  - run: |
      gh release download -R nextzlog/zylo -p ${{env.ZBUILD}}
      sudo chmod a+x ${{env.ZBUILD}}
      ./${{env.ZBUILD}} setup
      ./${{env.ZBUILD}} compile
      gh release upload ${{inputs.tag}} *.dll --clobber
    shell: bash
    env:
      ZBUILD: zbuild-${{runner.os}}
      GITHUB_TOKEN: ${{inputs.token}}
    working-directory: ${{inputs.directory}}
