name: 'build-zlog-plugin'
author: 'The University of Tokyo Amateur Radio Club'
description: 'GitHub action that builds a ZyLO DLL and publishes it as a nightly build'
branding:
  icon: radio
  color: blue
inputs:
  ref:
    description: 'branch'
  tag:
    description: 'release name'
    default: nightly
  version:
    description: 'zLog version'
    default: '2.8'
  token:
    description: 'GITHUB_TOKEN'
    required: true
  directory:
    description: 'project path'
    default: '.'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{inputs.ref}}
  - name: setup zbuild
    run: |
      mkdir -p .bin
      gh release download zbuild -R nextzlog/zylo
      sudo chmod a+x ${{env.ZBUILD}}
      mv ${{env.ZBUILD}} .bin/zbuild
      echo `pwd`/.bin >> $GITHUB_PATH
    shell: bash
    env:
      ZBUILD: zbuild-${{runner.os}}
      GITHUB_TOKEN: ${{inputs.token}}
  - run: sudo .bin/zbuild setup
    shell: bash
  - name: build plugin
    run: |
      zbuild compile ${{inputs.version}}
      gh release create ${{inputs.tag}} || true
      gh release upload ${{inputs.tag}} *.{dll,md5} --clobber
    shell: bash
    env:
      LATEST: zbuild -R nextzlog/zylo
      GITHUB_TOKEN: ${{inputs.token}}
    working-directory: ${{inputs.directory}}
