name: 'build-zlog-plugin'
author: 'The University of Tokyo Amateur Radio Club'
description: 'GitHub action that builds a ZyLO DLL and publishes it as a nightly build'
branding:
  icon: radio
  color: blue
inputs:
  ref:
    description: 'branch'
    required: false
    default: ''
  tag:
    description: 'release name'
    required: false
    default: nightly
  token:
    description: 'GITHUB_TOKEN'
    required: true
  directory:
    description: 'project path'
    required: false
    default: '.'
  nobuild:
    description: 'install only'
    required: false
    default: false
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{inputs.ref}}
    if: ${{inputs.nobuild == 'false'}}
  - name: setup zbuild
    run: |
      mkdir -p .bin
      gh release download -R nextzlog/zylo -p ${{env.ZBUILD}}
      sudo chmod a+x ${{env.ZBUILD}}
      mv ${{env.ZBUILD}} .bin/zbuild
      echo `pwd`/.bin >> $GITHUB_PATH
      echo `go env GOPATH`/bin >> $GITHUB_PATH
    shell: bash
    env:
      ZBUILD: zbuild-${{runner.os}}
      GITHUB_TOKEN: ${{inputs.token}}
  - run: sudo .bin/zbuild setup
    shell: bash
  - name: build plugin
    run: |
      zbuild compile
      gh release upload ${{inputs.tag}} *.dll --clobber
    shell: bash
    if: ${{inputs.nobuild == 'false'}}
    env:
      GITHUB_TOKEN: ${{inputs.token}}
    working-directory: ${{inputs.directory}}
