name: 'build-zlog-plugin'
author: 'The University of Tokyo Amateur Radio Club'
description: 'GitHub action that builds a ZyLO DLL and publishes it as a nightly build'
branding:
  icon: radio
  color: blue
inputs:
  ref:
    description: 'branch'
    required: false
    default: ''
  tag:
    description: 'release tag'
    required: false
    default: nightly
  token:
    description: 'GITHUB_TOKEN'
    required: true
  directory:
    description: 'source-file directory'
    required: false
    default: '.'
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{inputs.ref}}
  - uses: dsaltares/fetch-gh-release-asset@master
    with:
      repo: nextzlog/zylo
      file: zbuild-${{runner.os}}
      version: tags/zbuild
      token: ${{inputs.token}}
  - run: sudo chmod a+x zbuild-${{runner.os}}
    shell: bash
  - run: echo `pwd` >> $GITHUB_PATH
    shell: bash
  - run: zbuild-${{runner.os}} setup
    shell: bash
  - run: zbuild-${{runner.os}} compile
    shell: bash
    working-directory: ${{inputs.directory}}
  - uses: svenstaro/upload-release-action@v2
    with:
      tag: ${{inputs.tag}}
      file: ${{inputs.directory}}/*.dll
      file_glob: true
      overwrite: true
      repo_token: ${{inputs.token}}
