[package]
name = 'zbuild'
version = '0.0.1'
authors = ['JA1ZLO <nextzlog@gmail.com>']
edition = '2021'

[[bin]]
name = 'zbuild'
path = 'src/toolkit/zbuild.rs'

[dependencies]
argopt = '*'
md5 = '*'
minijinja = '*'
version-compare = '*'
