type: object
patternProperties:
  '^pkg$':
    type: object
    patternProperties:
      '':
        type: object
        properties:
          tag:
            type: string
          msg:
            type: string
          web:
            type: string
            format: uri
          use:
            type: array
            items:
              type: string
              pattern: '^(?!pkg\.)'
            minContains: 1
        required:
          - tag
          - msg
          - web
          - use
        additionalProperties: false
  '^(cfg|dat|dll|exe)$':
    type: object
    patternProperties:
      '':
        type: object
        properties:
          sum:
            type: string
          url:
            type: string
            format: uri
        required:
          - url
        additionalProperties: false
additionalProperties: false
