[pkg.aktest]
tag = "旭川コンテスト"
msg = "旭川コンテストの得点計算用の拡張機能です."
web = "https://github.com/nextzlog/zylo/tree/master/plugins/rules/aktest"
use = ["dll.aktest", "cfg.aktest"]
exp = "stable"

[cfg.aktest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/aktest/aktest.cfg"

[dll.aktest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/aktest.dll"

[pkg.hstest]
tag = "高校コンテスト"
msg = "高校コンテストの得点計算用の拡張機能です."
web = "https://github.com/nextzlog/zylo/tree/master/plugins/rules/hstest"
use = ["dll.hstest", "cfg.hstest"]
exp = "stable"

[cfg.hstest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/hstest/hstest.cfg"

[dll.hstest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/hstest.dll"

[pkg.tmtest]
tag = "東海マラソンコンテスト"
msg = "東海マラソンコンテストの得点計算用の拡張機能です."
web = "https://github.com/nextzlog/zylo/tree/master/plugins/rules/tmtest"
use = ["dll.tmtest", "cfg.tmtest"]
exp = "stable"

[cfg.tmtest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/tmtest/tmtest.cfg"

[dll.tmtest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/tmtest.dll"

[pkg.yltest]
tag = "YLコンテスト"
msg = "JLRS主催のYLコンテストの得点計算用の拡張機能です."
web = "https://github.com/nextzlog/zylo/tree/master/plugins/rules/yltest"
use = ["dll.yltest", "cfg.yltest"]
exp = "stable"

[cfg.yltest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/yltest/yltest.cfg"

[dll.yltest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/yltest.dll"

[pkg.rttest]
tag = "リアルタイムコンテスト"
msg = "リアルタイムコンテストのネットワーク接続機能を提供します."
web = "https://github.com/nextzlog/zylo/tree/master/plugins/rules/rttest"
use = ["dll.rttest", "cfg.rttest"]
exp = "stable"

[cfg.rttest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/rttest/rttest.cfg"

[dll.rttest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/rttest.dll"
