[exe.qxsl]
url = "https://github.com/nextzlog/qxsl/releases/download/nightly/qxsl.exe"

[pkg.format]
tag = "zLog additional I/O"
msg = "CTESTWINのLG8やHAMLOGのHDBを始め, 様々なファイルへの対応をzLogのインポート・エクスポート機能に追加します."
web = "https://github.com/nextzlog/zylo"
use = ["dll.format", "exe.qxsl"]
exp = "stable"

[dll.format]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/format.dll"
sum = "https://github.com/nextzlog/zylo/releases/download/nightly/format.dll.md5"

[pkg.latest]
tag = "zLog update checker"
msg = "zLogの最新のリリースを自動的に検出し, デスクトップの通知欄に表示します."
web = "https://github.com/nextzlog/zylo"
use = ["dll.latest"]
exp = "stable"

[dll.latest]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/latest.dll"
sum = "https://github.com/nextzlog/zylo/releases/download/nightly/latest.dll.md5"

[pkg.maplot]
tag = "Maplot"
msg = "zLogで記録したQSOから, 交信済みのJCC/Gコードを検出し, 地図に描画します."
web = "https://github.com/nextzlog/zylo"
use = ["dll.maplot"]
exp = "stable"

[dll.maplot]
url = "https://github.com/nextzlog/zylo/releases/download/nightly/maplot.dll"
sum = "https://github.com/nextzlog/zylo/releases/download/nightly/maplot.dll.md5"
