remote_theme: autodyne/pafe
url: https://nextzlog.github.io/zylo
name: ZyLO
icon: /assets/head.png
lead: &desc ZyLOはWindowsで動作するコンテスト用ロギングソフトzLog令和版のプラグインを開発するためのフレームワークです。
desc: *desc
links:
- name: GitHub
  href: https://github.com/nextzlog/zylo
  icon: fab fa-github
- name: zLog.org
  href: https://zlog.org
- name: 無線部開発班
  href: https://nextzlog.dev
