name: 'zbuild'
on:
  push:
    branches:
    - 'master'
jobs:
  BuildZyLO:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          asset: zbuild-macos
        - os: ubuntu-latest
          asset: zbuild-ubuntu
        - os: windows-latest
          asset: zbuild-windows.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: rustc zbuild.rs -o ${{matrix.asset}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.asset}}
        path: ${{matrix.asset}}
    - uses: svenstaro/upload-release-action@v2
      with:
        tag: zbuild
        file: ${{matrix.asset}}
        repo_token: ${{secrets.GITHUB_TOKEN}}
        overwrite: true
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: format
        - name: hstest
        - name: latest
        - name: rttest
        - name: toasty
        - name: yltest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/download-artifact@v2
      with:
        name: zbuild-ubuntu
    - run: sudo chmod a+x zbuild-ubuntu
    - run: ../../zbuild-ubuntu
      working-directory: rules/${{matrix.name}}
    - uses: crazy-max/ghaction-upx@v1
      with:
        files: rules/${{matrix.name}}/*.dll
        args: --lzma -fq
    - uses: svenstaro/upload-release-action@v2
      with:
        tag: nightly
        file: rules/${{matrix.name}}/*.dll
        file_glob: true
        overwrite: true
        repo_token: ${{secrets.GITHUB_TOKEN}}
  Documents:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
    - run: go get github.com/robertkrimen/godocdown/godocdown
    - run: mkdir doc && godocdown > doc/README.md
    - uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: true
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: doc
