name: 'build'
on:
  push:
    branches:
    - 'master'
jobs:
  BuildZyLO:
    if: github.event_name == 'push'
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          name: zbuild-macos
          path: target/release/zbuild
        - os: ubuntu-latest
          name: zbuild-linux
          path: target/release/zbuild
        - os: windows-latest
          name: zbuild-windows.exe
          path: target/release/zbuild.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.name}}
        path: ${{matrix.path}}
    - uses: svenstaro/upload-release-action@v2
      with:
        tag: zbuild
        file: ${{matrix.path}}
        asset_name: ${{matrix.name}}
        repo_token: ${{secrets.GITHUB_TOKEN}}
        overwrite: true
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: plugins/rules/hstest
        - name: plugins/rules/rttest
        - name: plugins/rules/tmtest
        - name: plugins/rules/yltest
        - name: plugins/utils/format
        - name: plugins/utils/latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/download-artifact@v2
      with:
        name: zbuild-linux
    - run: chmod a+x zbuild
    - run: ./zbuild setup
    - run: ./zbuild compile ${{matrix.name}}
    - uses: svenstaro/upload-release-action@v2
      with:
        tag: nightly
        file: ${{matrix.name}}/*.dll
        file_glob: true
        overwrite: true
        repo_token: ${{secrets.GITHUB_TOKEN}}
  Documents:
    needs: BuildDemo
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        event-type: store
