name: 'build'
on:
  push:
    branches:
    - 'master'
  schedule:
  - cron: '0 0 * * *'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  BuildZyLO:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          name: zbuild-macOS
          path: target/release/zbuild
        - os: ubuntu-latest
          name: zbuild-Linux
          path: target/release/zbuild
        - os: windows-latest
          name: zbuild-Windows.exe
          path: target/release/zbuild.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: |
        cargo build --release
        mv ${{matrix.path}} ${{matrix.name}}
        gh release upload zbuild ${{matrix.name}} --clobber
      working-directory: zbuild
      if: github.event_name == 'push'
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: plugins/rules/aktest
        - name: plugins/rules/hstest
        - name: plugins/rules/rttest
          zlog: 2.8.3.0
        - name: plugins/rules/tmtest
        - name: plugins/rules/yltest
        - name: plugins/utils/format
        - name: plugins/utils/latest
        - name: plugins/utils/maplot
          zlog: 2.8.3.0
        - name: plugins/utils/prefix
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        version: ${{matrix.zlog}}
        directory: ${{matrix.name}}
      if: github.event_name == 'push'
  BuildJSON:
    needs: BuildDemo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: zylo
    - uses: actions/checkout@v2
      with:
        path: zlog
        repository: jr8ppg/zlog
    - uses: nextzlog/zylo@master
      with:
        nobuild: true
        token: ${{secrets.GITHUB_TOKEN}}
    - run: cp zlog/zlog/main.dfm zylo
    - run: |
        mkdir -p _includes
        zbuild market > market.json
        grep object ../main.dfm > _includes/form.dfm
      working-directory: zylo/docs
    - name: publish docs
      run: |
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o _morse.md -template docs/_morse.md commons/morse
        godocdown -o _reiwa.md -template docs/_reiwa.md commons/reiwa
        godocdown -o _win32.md -template docs/_win32.md commons/win32
        cat _*.md >> docs/index.md
      working-directory: zylo
    - uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: true
        publish_dir: zylo/docs
        cname: zylo.pafelog.net
        github_token: ${{secrets.GITHUB_TOKEN}}
