name: build
on:
  push:
    branches:
    - master
permissions:
  contents: write
  id-token: write
  pages: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  BuildZyLO:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          name: zbuild-macOS
          path: target/release/zbuild
        - os: ubuntu-latest
          name: zbuild-Linux
          path: target/release/zbuild
        - os: windows-latest
          name: zbuild-Windows.exe
          path: target/release/zbuild.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: |
        cargo build --release
        mv ${{matrix.path}} ${{matrix.name}}
        gh release create zbuild || true
        gh release upload zbuild ${{matrix.name}} --clobber
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: src/plugins/rules/aktest
        - name: src/plugins/rules/hstest
        - name: src/plugins/rules/rttest
          zlog: 2.8.3.0
        - name: src/plugins/rules/tmtest
        - name: src/plugins/rules/yltest
        - name: src/plugins/utils/format
        - name: src/plugins/utils/latest
        - name: src/plugins/utils/maplot
          zlog: 2.8.3.0
        - name: src/plugins/utils/prefix
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        version: ${{matrix.zlog}}
        directory: ${{matrix.name}}
  BuildPage:
    needs: BuildDemo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
      with:
        path: zylo
    - uses: actions/checkout@v2
      with:
        path: zlog
        repository: jr8ppg/zlog
    - run: |
        mkdir -p _includes
        cp ${GITHUB_WORKSPACE}/zlog/zlog/main.dfm _includes
        grep object _includes/main.dfm > _includes/form.dfm
      working-directory: zylo/src/manuals
    - name: publish manuals
      run: |
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o _morse.md -template manuals/_morse.md commons/morse
        godocdown -o _reiwa.md -template manuals/_reiwa.md commons/reiwa
        godocdown -o _win32.md -template manuals/_win32.md commons/win32
        cat _*.md >> manuals/index.md
      working-directory: zylo/src
    - uses: actions/configure-pages@v2
    - uses: actions/jekyll-build-pages@v1
      with:
        source: zylo/src/manuals
    - uses: actions/upload-pages-artifact@v1
  Publish:
    needs: BuildPage
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/deploy-pages@v1
