name: 'build'
on:
  push:
    branches:
    - 'master'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  BuildZyLO:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          name: zbuild-macOS
          path: target/release/zbuild
        - os: ubuntu-latest
          name: zbuild-Linux
          path: target/release/zbuild
        - os: windows-latest
          name: zbuild-Windows.exe
          path: target/release/zbuild.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: |
        cargo build --release
        mv ${{matrix.path}} ${{matrix.name}}
        gh release upload zbuild ${{matrix.name}} --clobber
      working-directory: zbuild
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: plugins/rules/aktest
        - name: plugins/rules/hstest
        - name: plugins/rules/rttest
        - name: plugins/rules/tmtest
        - name: plugins/rules/yltest
        - name: plugins/utils/format
        - name: plugins/utils/latest
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        directory: ${{matrix.name}}
  Documents:
    needs: BuildDemo
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        event-type: store
