name: 'build'
on:
  push:
    branches:
    - 'master'
  gollum:
  schedule:
  - cron: '0 0 * * *'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  BuildZyLO:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - os: macos-latest
          name: zbuild-macOS
          path: target/release/zbuild
        - os: ubuntu-latest
          name: zbuild-Linux
          path: target/release/zbuild
        - os: windows-latest
          name: zbuild-Windows.exe
          path: target/release/zbuild.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: |
        cargo build --release
        mv ${{matrix.path}} ${{matrix.name}}
        gh release upload zbuild ${{matrix.name}} --clobber
      working-directory: zbuild
      if: github.event_name == 'push'
  BuildDemo:
    needs: BuildZyLO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: plugins/rules/aktest
        - name: plugins/rules/hstest
        - name: plugins/rules/rttest
          zlog: 2.8.3.0
        - name: plugins/rules/tmtest
        - name: plugins/rules/yltest
        - name: plugins/utils/format
        - name: plugins/utils/latest
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        version: ${{matrix.zlog}}
        directory: ${{matrix.name}}
      if: github.event_name == 'push'
  FetchWiki:
    needs: BuildDemo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - repo: jr8ppg/zlog
          name: form
          file: zlog/main.dfm
        - repo: jr8ppg/zlog.wiki
          name: zlog
          file: Home.md
        - repo: nextzlog/zylo.wiki
          name: zylo
          file: Home.md
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{matrix.repo}}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}
        path: ${{matrix.file}}
  FetchRepo:
    needs: FetchWiki
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - repo: repos/jr8ppg/zlog/releases
          name: zlog
          file: builds.json
        - repo: repos/jr8ppg/zlog/issues
          name: zlog
          file: issues.json
        - repo: repos/nextzlog/todo/issues
          name: zylo
          file: issues.json
    steps:
    - run: gh api ${{matrix.repo}} --paginate > ${{matrix.file}}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}
        path: ${{matrix.file}}
  Documents:
    needs: FetchRepo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nextzlog/zylo@master
      with:
        nobuild: true
        token: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/download-artifact@v3
      with:
        path: web/_includes
    - run: |
        mkdir _data && mv _includes/zlog/builds.json _data
        mkdir _data/zlog && mv _includes/zlog/issues.json _data/zlog
        mkdir _data/zylo && mv _includes/zylo/issues.json _data/zylo
        zbuild market | tee market.json _data/market.json
        jq -s add _data/*/issues.json > _data/issues.json
      working-directory: web
      if: github.event_name != 'gollum'
    - run: grep object main.dfm > form.dfm
      working-directory: web/_includes/form
    - name: publish docs
      run: |
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o web/manual.md -template web/manual.md zbuild/src
    - uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: true
        cname: zylo.pafelog.net
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: web
        keep_files: true
