name: 'store'
on:
  schedule:
  - cron: '0 0 * * *'
  repository_dispatch:
    types:
    - store
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  UpdateWeb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        gh release download -p ${{env.ZBUILD}}
        sudo chmod a+x ${{env.ZBUILD}}
        ./${{env.ZBUILD}} setup
        ./${{env.ZBUILD}} market > web/market.json
        echo `go env GOPATH`/bin >> $GITHUB_PATH
      env:
        ZBUILD: zbuild-${{runner.os}}
    - run: |
        echo '{{.EmitUsage}}' >> temp.md
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o godoc.md -template temp.md zbuild/src
        sed -i -e "s/Usage/API/g" -e "s/^##/#/g" godoc.md
        cat MANUAL.md godoc.md > web/manual.md
    - uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: true
        cname: zylo.pafelog.net
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: web
