name: 'store'
on:
  schedule:
  - cron: '0 0 * * 6'
  repository_dispatch:
    types:
    - store
jobs:
  UpdateWeb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        file: 'zbuild-Linux'
        token: ${{secrets.GITHUB_TOKEN}}
        version: 'tags/zbuild'
    - run: sudo chmod a+x zbuild-Linux
    - run: ./zbuild-Linux setup
    - run: ./zbuild-Linux market > web/market.json
    - run: echo `go env GOPATH`/bin >> $GITHUB_PATH
    - run: echo '# ZyLO API' >> temp.md
    - run: echo '{{.EmitUsage}}' >> temp.md
    - run: go get github.com/robertkrimen/godocdown/godocdown
    - run: godocdown -o godoc.md -template temp.md zbuild/src
    - run: cat MANUAL.md godoc.md > web/MANUAL.md
    - uses: peaceiris/actions-gh-pages@v3
      with:
        cname: zylo.pafelog.net
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: web
