name: 'store'
on:
  schedule:
  - cron: '0 0 * * *'
  gollum:
  repository_dispatch:
    types:
    - store
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  UpdateWeb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup zbuild
      run: |
        gh release download -p ${{env.ZBUILD}}
        sudo chmod a+x ${{env.ZBUILD}}
        ./${{env.ZBUILD}} setup
        echo `go env GOPATH`/bin >> $GITHUB_PATH
      env:
        ZBUILD: zbuild-${{runner.os}}
    - name: publish docs
      run: |
        mkdir web/_data
        gh api repos/jr8ppg/zlog/releases > web/_data/builds.json
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o web/manual.md -template web/manual.md zbuild/src
        git submodule add https://github.com/nextzlog/zylo.wiki web/wiki
    - name: crawl market
      run: |
        ./${{env.ZBUILD}} market > web/market.json
        cp web/market.json web/_data
      env:
        ZBUILD: zbuild-${{runner.os}}
      if: github.event_name != 'gollum'
    - uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: true
        cname: zylo.pafelog.net
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: web
        keep_files: true
